name: Add check approval workflow
on: pull_request
jobs:
  add-check-approval-workflow:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            .github/workflows
      - uses: szksh-lab/validate-pr-review-action/add-check-approval@main
      - uses: csm-actions/securefix-action@4f3e711a06d7d5a3f5527cc622f6c75362fec74b # v0.3.6
        with:
          app_id: ${{ vars.AUTOFIX_TRIGGER_APP_ID }}
          app_private_key: ${{ secrets.AUTOFIX_TRIGGER_APP_PRIVATE_KEY }}
          server_repository: securefix-server-workflow
          commit_message: "ci: add or update check-approval workflow"
          files: |
            .github/workflows/check-approval.yaml
