name: Add check approval workflow
on: pull_request
jobs:
  add-check-approval-workflow:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            .github/workflows
      - uses: szksh-lab/validate-pr-review-action/add-check-approval@main
      - uses: csm-actions/securefix-action@949d3cfb554abee10f695014674759978ba8ba34 # v0.4.1
        with:
          app_id: ${{ vars.AUTOFIX_TRIGGER_APP_ID }}
          app_private_key: ${{ secrets.AUTOFIX_TRIGGER_APP_PRIVATE_KEY }}
          server_repository: securefix-server-workflow
          commit_message: "ci: add or update check-approval workflow"
          files: |
            .github/workflows/check-approval.yaml
